### ISSUE TITLE
Problem when upload file

### ISSUE THREAD

**Issue by PandasCoder** [nhost/hasura-storage#237]
i'm having the following message trying to upload a file

time="2025-05-03T03:25:15Z" level=error msg="call completed with some errors" client_ip=172.18.0.1 errors="[problem processing request: problem initializing file metadata: failed to decode data \x1bD\x00\x00\xe4mz\xfd\xfeBe6\x8c\x7f\xcf/i\x10\x8c\x1d[_X\x13\x89\x14\x0f\x1d0\xdd\n\xfd\xc0z\x7f\xff\xf6\xbd\x1e\xaf\x06\x1d\x12M-4\x15\xdb \xc3*\x9cQ\xb21\x8a'.J\xa3^M \"\x00: invalid character '\\x1b' looking for beginning of value]" latency_time=905.84485ms method=POST status_code=500 url=/v1/files

the register creates on the hasura server but then shows that message

![Image](https://github.com/user-attachments/assets/f8d4cfe3-d4fe-460d-a448-dd4f856ddf4e)

i'm using the version of hasura-storage 0.7.1 i'm also tried with the 0.7.0 and 0.6.0

this is part of my compose configuration 

``` yaml
  nhost_storage:
    image: nhost/hasura-storage:0.6.0
    container_name: nhost_storage
    command: 
      - serve
    restart: always
    profiles: ["nhost", "all"]
    depends_on:
      - nhost_graphql
      - nhost_minio
    environment:
      DEBUG: "true"
      BIND: :5000
      HASURA_ENDPOINT: https://hasura.codea.plus/v1
      HASURA_GRAPHQL_ADMIN_SECRET: ${NHOST_HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_METADATA: "1"
      POSTGRES_MIGRATIONS: "1"
      POSTGRES_MIGRATIONS_SOURCE: postgres://postgres:${NHOST_POSTGRES_PASSWORD}@nhost_postgres:5432/postgres?sslmode=disable
      PUBLIC_URL: ${NHOST_STORAGE_PUBLIC_URL}
      S3_ACCESS_KEY: ${NHOST_MINIO_ROOT_USER}
      S3_BUCKET: ${NHOST_STORAGE_S3_BUCKET:-default}
      S3_ENDPOINT: http://minio:9000
      S3_REGION: "us-east-1"
      S3_ROOT_FOLDER: ""
      S3_SECRET_KEY: ${NHOST_MINIO_ROOT_PASSWORD}
      CLAMAV_SERVER: tcp://nhost_clamd:3310
    networks:
      - default
    ports:
      - '9093:5000'
```
